Julio Veganos e Hijos interfaz: Dashboard Class Reference
Dashboard Class Reference
#include <Dashboard.h>
Public Member Functions
Dashboard ()
void cabecera ()
Principal header with the name of the business.
void set_dashboardEmployer ()
Set the menu for the employers.
void set_dashboardAdmin ()
Set the menu for the Admins.
void dashboard (DataBase *, bool)
Dashboard (Dashboard &otherDashboard)=delete
void operator= (const Dashboard &)=delete
Static Public Member Functions
static Dashboard * getTheDashboard ()
Private Member Functions
void goToSecurity ()
Menu with options for the security.
void goToSensors ()
menu that shows the different sensors. For each instruction a sensor is shown
void goOut ()
Function to exit the program when the option is selected.
void goBack ()
void eraseUserDashboard ()
Method that allow the admin to erase the users.
void addUserDashboard ()
Function that allows the admin to add new users.
Private Attributes
int opcion
int pantalla
DataBase * database
Static Private Attributes
static Dashboard * singleDashboard = nullptr
Detailed Description
Definition at line 19 of file Dashboard.h.
Constructor & Destructor Documentation
Dashboard() [1/2]
Dashboard::Dashboard ()
Definition at line 27 of file Dashboard.cpp.
 {}
Dashboard() [2/2]
Dashboard::Dashboard (Dashboard & otherDashboard) delete
Member Function Documentation
addUserDashboard()
void Dashboard::addUserDashboard () private
Function that allows the admin to add new users.
Definition at line 263 of file Dashboard.cpp.
{
     while (true) {
         cabecera();
         database->userList();
         cout << "\n----------------------------------------------------------------------------------------------------\n" << endl;
         cout << "Si desea añadir un usuario introduzca 1, para salir introduzca 0" << endl;
         cout << ">>> ";
         cin >> opcion;
         try {
             switch (opcion)
             {
             case 1:
                 cout << "Introduzca ID del nuevo usuario" << endl;
                 cout << ">>> ";
                 cin >> database->nuevoID;
                 cout << database->nuevoID << endl;
                 cout << "Introduzca NIF del nuevo usuario" << endl;
                 cout << ">>> ";
                 cin >> database->nuevoNIF;
                 cout << database->nuevoNIF << endl;
                 cout << "¿El usuario es adiministrador? (introduzaca 0 para NO, 1 para SI" << endl;
                 cout << ">>> ";
                 cin >> database->admin;
                 database->addUser();
                 break;
             case 0:
                 return;
             default:
                 throw instructionException();
             }
         } catch (instructionException &except) {
             cout << "Exception: " << except.what() << endl;
             system("sleep 2");
         }
     }
 }
References DataBase::addUser(), DataBase::admin, database, DataBase::nuevoID, DataBase::nuevoNIF, opcion, and DataBase::userList().
cabecera()
void Dashboard::cabecera ()
Principal header with the name of the business.
Definition at line 41 of file Dashboard.cpp.
{
     system("clear");
     cout << "\x1b[32m                                                                                         \n"
 "          / /                          ||   / /                                                      \n"
 "         / /          // ( )  ___      ||  / /  ___      ___      ___       __      ___      ___     \n"
 "        / / //   / / // / / //   ) )   || / / //___) ) //   ) ) //   ) ) //   ) ) //   ) ) ((   ) )  \n"
 "       / / //   / / // / / //   / /    ||/ / //       ((___/ / //   / / //   / / //   / /   \\ \\    \n"
 " ((___/ / ((___( ( // / / ((___/ /     |  / ((____     //__   ((___( ( //   / / ((___/ / //   ) )    \n"
 "                                                                                                     \n"
 "                         //    / /                                                                   \n"
 "            ___         //___ / / ( )     ( )  ___      ___                                          \n"
 "          //___) )     / ___   / / /     / / //   ) ) ((   ) )                                       \n"
 "         //           //    / / / /     / / //   / /   \\ \\                                         \n"
 "        ((____       //    / / / / ((  / / ((___/ / //   ) )    \x1b[0m                            \n\n"
 "---------------------------------------------------------------------------------------------------- \n" << endl;
 };
dashboard()
void Dashboard::dashboard (DataBase * base, bool isAdmin)
Definition at line 301 of file Dashboard.cpp.
{
     database = base;
     if (isAdmin) {
         set_dashboardAdmin();
     } else {
         set_dashboardEmployer();
     }
 }
References database.
eraseUserDashboard()
void Dashboard::eraseUserDashboard () private
Method that allow the admin to erase the users.
Definition at line 234 of file Dashboard.cpp.
{
     while (true) {
         int opcion;
         cabecera();
         database->userList();
         cout << "\n----------------------------------------------------------------------------------------------------\n" << endl;
         cout << "\nIntroduzca el ID del usuario que desa borrar o introduzca 0 para volver" << endl;
         cout << database->actualID << endl;
         cout << ">>> ";
         cin >> opcion;
         try {
             switch (opcion) {
             case 0:
                 return;
             default:
                 if (database->actualID == opcion) {
                     throw actualUserException();
                     break;
                 } else {
                     database->eraseUser(opcion);
                 }
             }
         } catch  (actualUserException &except) {
             cout << "Exception: " << except.what() << endl;
             system("sleep 2");
         }
     }
 }
References DataBase::actualID, database, DataBase::eraseUser(), opcion, and DataBase::userList().
getTheDashboard()
Dashboard * Dashboard::getTheDashboard () static
Definition at line 312 of file Dashboard.cpp.
{
     if (singleDashboard == nullptr)
         singleDashboard = new Dashboard ();
     else
         cout << "Error: trying to get another instance of a Ball singleton class!\n";
     return singleDashboard;
 }
goBack()
void Dashboard::goBack () private
goOut()
void Dashboard::goOut () private
Function to exit the program when the option is selected.
Definition at line 227 of file Dashboard.cpp.
                       {
     system("clear");
     cout << "\x1b[41mSaliendo del sistema...\x1b[0m" << endl;
     database->writeUsers();
     exit(0);
 }
References database, and DataBase::writeUsers().
goToSecurity()
void Dashboard::goToSecurity () private
Menu with options for the security.
Definition at line 187 of file Dashboard.cpp.
{
     while (true) {
         // Heading and options
         cabecera();
         cout << "\t\tOPCIONES DISPONIBLES\n\t\t-Puertas\t==> 1\n\t\t-Ventanas\t==> 2\n\t\t-Camaras\t==> 3\n\t\t-Alarma\t\t==> 4\n\t\t-Exit\t\t==> 0" << endl;
         cout << "\n----------------------------------------------------------------------------------------------------\n" << endl;
         cout << "Seleccione una opcion escribiendo el número correspondiente.\n" << endl;
         cout << ">>> ";
         cin >> opcion;
         try {
             switch (opcion) {
             case 0:
                 return;
             case 1:
                 cabecera();
                 s.security("puertas");
                 break;
             case 2:
                 cabecera();
                 s.security("ventanas");
                 break;
             case 3:
                 cabecera();
                 s.security("camaras");
                 break;
             case 4:
                 cabecera();
                 s.security("alarma");
                 break;
             default:
                 throw instructionException();
             }
         } catch (instructionException &except) {
             cout << "Exception: " << except.what() << endl;
             system("sleep 2");
         }
     }
 };
References opcion, s, and Security::security().
goToSensors()
void Dashboard::goToSensors () private
menu that shows the different sensors. For each instruction a sensor is shown
Definition at line 133 of file Dashboard.cpp.
{
     while (true) {
         // Heading and options
         cabecera();
         cout << "\t\tOPCIONES DISPONIBLES\n\t\t-Humidity\t==> 1 \n\t\t-Brightness\t==> 2 \n\t\t-Air Quality\t==> 3 \n\t\t-Temperature\t==> 4 \n\t\t-RBG cam\t==> 5 \n\t\t-Termal cam\t==> 6 \n\t\t-Exit\t\t==> 0" << endl;
         cout << "\n----------------------------------------------------------------------------------------------------\n" << endl;
         cout << "Seleccione una opcion escribiendo el número correspondiente.\n" << endl;
         cout << ">>> ";
         cin >> opcion;
         try {
             switch (opcion) {
             case 0:
             return;
             case 1:
                 cabecera();
                 hum.getData();
                 break;
             case 2:
                 cabecera();
                 brigh.getData();
                 break;
             case 3:
                 cabecera();
                 airq.getData();
                 break;
             case 4:
                 cabecera();
                 temp.getData();
                 break;
             case 5:
                 cabecera();
                 sen.getData(opcion);
                 break;
             case 6:
                 cabecera();
                 sen.getData(opcion);
                 break;
             default:
                 throw instructionException();
             }
         } catch (instructionException &except) {
             cout << "Exception: " << except.what() << endl;
             system("sleep 2");
         }
     }
 };
References airq, brigh, AirQuality::getData(), Brightness::getData(), Humidity::getData(), Temperature::getData(), Sensor::getData(), hum, opcion, sen, and temp.
operator=()
void Dashboard::operator= (const Dashboard &) delete
set_dashboardAdmin()
void Dashboard::set_dashboardAdmin ()
Set the menu for the Admins.
Definition at line 93 of file Dashboard.cpp.
{
     while (true) {
         cabecera();
         cout << "\t\tOPCIONES DISPONIBLES\n\t\t-Sensores\t==> 1\n\t\t-Seguridad\t==> 2\n\t\t-Add Users\t==> 3\n\t\t-Erase Users\t==> 4\n\t\t-Cerrar Sesión\t==> 5\n\t\t-Exit\t\t==> 0\n\t\t" << endl;
         cout << "----------------------------------------------------------------------------------------------------\n" << endl;
         cout << "Seleccione una opcion escribiendo el número correspondiente.\n" << endl;
         cout << ">>> ";
         cin >> opcion;
         try {
         switch (opcion) {
         case 0:
             goOut();
             break;
         case 1:
             goToSensors();
             break;
         case 2:
             goToSecurity();
             break;
         case 3:
             addUserDashboard();
             break;
         case 4:
             eraseUserDashboard();
             break;
         case 5:
             return;
         default:
                 throw instructionException();
             }
         } catch (instructionException &except) {
             cout << "Exception: " << except.what() << endl;
             system("sleep 2");
         }
     }
 };
References opcion.
set_dashboardEmployer()
void Dashboard::set_dashboardEmployer ()
Set the menu for the employers.
Definition at line 61 of file Dashboard.cpp.
{
     while (true) {
         cabecera();
         cout << "\t\tOPCIONES DISPONIBLES\n\t\t-Sensores\t==> 1\n\t\t-Seguridad\t==> 2\n\t\t-Cerrar Sesión\t==> 3\n\t\t-Exit\t\t==> 0\n\t\t" << endl;
         cout << "----------------------------------------------------------------------------------------------------\n" << endl;
         cout << "Seleccione una opcion escribiendo el número correspondiente.\n" << endl;
         cout << ">>> ";
         cin >> opcion;
         try {
         switch (opcion) {
         case 0:
             goOut();
             break;
         case 1:
             goToSensors();
             break;
         case 2:
             goToSecurity();
             break;
         case 3:
             return;
         default:
                 throw instructionException();
             }
         } catch (instructionException &except) {
             cout << "Exception: " << except.what() << endl;
             system("sleep 2");
         }
     }
 };
References opcion.
Member Data Documentation
database
DataBase* Dashboard::database private
Definition at line 82 of file Dashboard.h.
opcion
int Dashboard::opcion private
Definition at line 80 of file Dashboard.h.
pantalla
int Dashboard::pantalla private
Definition at line 81 of file Dashboard.h.
singleDashboard
Dashboard * Dashboard::singleDashboard = nullptr static private
Definition at line 84 of file Dashboard.h.
The documentation for this class was generated from the following files:
include/Dashboard.h
src/Dashboard.cpp