Julio Veganos e Hijos interfaz: Security Class Reference
Security Class Reference
#include <Security.h>
Public Member Functions
Security ()
void security (string)
Depend on the instruction, the security class shows a different menu.
Public Attributes
string seguridad
Private Member Functions
void door ()
void window ()
void camera ()
void alarm ()
void open_close ()
int generate_random ()
Generate a random value and depend on it in some methods is used to generate a true or false value.
void goBackSecurity ()
Private Attributes
string open
string alarma_status
Detailed Description
Definition at line 17 of file Security.h.
Constructor & Destructor Documentation
Security()
Security::Security ()
Definition at line 24 of file Security.cpp.
 {}
Member Function Documentation
alarm()
void Security::alarm () private
Definition at line 118 of file Security.cpp.
                      {
     while (true) {
         cout << "\n\tAlarma: " << alarm_status << "\n\n" << endl;
         cout << "Para encender introduzca 1, para apagar introduzca 2, para salir 0\n" << endl;
         cout << ">>> ";
         cin >> entrada;
         switch (entrada) {
         case 0:
             return;
         case 1:
             alarm_status = "encendido";
             db.cabecera();
             break;
         case 2:
             alarm_status = "apagado";
             db.cabecera();
             break;
         default:
             cout << "Orden incorrecta" << endl;
             system("sleep 1");
             db.cabecera();
             break;
         }
     }
 }
References alarm_status, Dashboard::cabecera(), db, and entrada.
camera()
void Security::camera () private
Definition at line 100 of file Security.cpp.
                       {
     while (true) {
         cout << "Imagina que hay una camara" << endl;
         cout << "\n\t\tPara volver atrás introduzca 0 + ENTER" << endl;
         cin >> back;
         switch (back) {
         case 0:
             return;
             break;
         default:
             cout << "Orden incorrecta" << endl;
             system("sleep 1");
             db.cabecera();
             break;
         }
     }
 }
References back, Dashboard::cabecera(), and db.
door()
void Security::door () private
Definition at line 42 of file Security.cpp.
                     {
     while (true) {
         open_close();
         cout << "Puerta: 01\tLocalización: Huerto\tEstado: " << open << endl;
         open_close();
         cout << "Puerta: 02\tLocalización: Almacen\tEstado: " << open << endl;
         open_close();
         cout << "Puerta: 03\tLocalización: Despacho\tEstado: " << open << endl;
         cout << "\n\t\tPara volver atrás introduzca 0 + ENTER" << endl;
         cout << ">>> ";
         cin >> back;
         // If an order different of 0 is inserted, the door menu is restarted.
         switch (back) {
         case 0:
             return;
             break;
         default:
             cout << "Orden incorrecta" << endl;
             system("sleep 1");
             db.cabecera();
             break;
         }
     }
 }
References back, Dashboard::cabecera(), db, and open.
generate_random()
int Security::generate_random () private
Generate a random value and depend on it in some methods is used to generate a true or false value.
Returns
int
Definition at line 148 of file Security.cpp.
{
     srand(time(NULL));
     return rand()%10;
 }
goBackSecurity()
void Security::goBackSecurity () private
open_close()
void Security::open_close () private
Definition at line 154 of file Security.cpp.
{
     int random = generate_random();
     if (random >= 0 && random <= 4) {
         open = "close";
     } else {
         open = "open";
     }
 }
References open.
security()
void Security::security (string seguridad)
Depend on the instruction, the security class shows a different menu.
Parameters
string seguridad, depending on it's "value" the class shows a different menu
Definition at line 29 of file Security.cpp.
{
     if (seguridad == "puertas") {
         door();
     } else if (seguridad == "ventanas") {
         window();
     } else if (seguridad == "camaras") {
         camera();
     } else if (seguridad == "alarma") {
         alarm();
     }
 }
References seguridad.
window()
void Security::window () private
Definition at line 72 of file Security.cpp.
                       {
     while (true) {
         open_close();
         cout << "Ventana: 01\tLocalización: Huerto\tEstado: " << open << endl;
         open_close();
         cout << "Ventana: 02\tLocalización: Almacen\tEstado: " << open << endl;
         open_close();
         cout << "Ventana: 03\tLocalización: Despacho\tEstado: " << open << endl;
         cout << "\n\t\tPara volver atrás introduzca 0 + ENTER" << endl;
         cin >> back;
         // if an order different of 0 the programm restart
         switch (back) {
         case 0:
             return;
             break;
         default:
             cout << "Orden incorrecta" << endl;
             system("sleep 1");
             db.cabecera();
             break;
         }
     }
 }
References back, Dashboard::cabecera(), db, and open.
Member Data Documentation
alarma_status
string Security::alarma_status private
Definition at line 49 of file Security.h.
open
string Security::open private
Definition at line 48 of file Security.h.
seguridad
string Security::seguridad
Definition at line 20 of file Security.h.
The documentation for this class was generated from the following files:
include/Security.h
src/Security.cpp