Julio Veganos e Hijos interfaz: DataBase Class Reference
DataBase Class Reference
#include <DataBase.h>
Public Member Functions
DataBase ()
Construct a new Data Base object.
void userList ()
list of the current usersd
void readUsers ()
Method to read the current users from the file users.dat.
void writeUsers ()
Methot used for write in the file users.dat the users at the end of the program.
bool validUser (int, int)
Validates the users credentials that are stored in the database.
void eraseUser (int)
method to erase users
void addUser ()
Method to add new users.
Public Attributes
bool valided
bool to return the
int nuevoID
int nuevoNIF
int admin
bool isAdmin
int actualID
User that is used to login.
Private Attributes
std::set< User > vectorUser
Users storage.
Detailed Description
Definition at line 22 of file DataBase.h.
Constructor & Destructor Documentation
DataBase()
DataBase::DataBase ()
Construct a new Data Base object.
Definition at line 25 of file DataBase.cpp.
                    {
     /*User* user1 = new User(1111, 12345678, 0);
     User* user2 = new User(2222, 23456789, 0);
     User* user3 = new User(3333, 34567890, 0);
     User* user4 = new User(1212, 12121212, 1);
     vectorUser.insert(*user1);
     vectorUser.insert(*user2);
     vectorUser.insert(*user3);
     vectorUser.insert(*user4);*/
 }
Member Function Documentation
addUser()
void DataBase::addUser ()
Method to add new users.
Definition at line 73 of file DataBase.cpp.
{
     for (User u : vectorUser) {
         if (u.getUserID() == nuevoID || u.getUserNIF() == nuevoNIF) {
             cout << "ID o NIF ya existentes" << endl;
             break;
         } else {
             vectorUser.insert(User(nuevoNIF, nuevoID, admin));
         }
     }
 }
References admin, nuevoID, and nuevoNIF.
eraseUser()
void DataBase::eraseUser (int posicion)
method to erase users
Definition at line 63 of file DataBase.cpp.
{
     for (User u : vectorUser) {
         if (posicion == u.getUserID() ) {
             vectorUser.erase(u);
             break;
         }
     }
 }
readUsers()
void DataBase::readUsers ()
Method to read the current users from the file users.dat.
Definition at line 88 of file DataBase.cpp.
{
     ifstream inUsersFile ("./resources/users.dat", ios::in | ios::binary);
     if (!inUsersFile) { // file couldn't be opened
         cerr << "File could not be opened" << endl;
         exit (1);
     }
     User user;
     inUsersFile.read (reinterpret_cast <char *>(&user), sizeof (User));
     while (inUsersFile && !inUsersFile.eof()) {
         if (user.getNumRecord() != 0) {
             vectorUser.insert (user);
         }
         inUsersFile.read (reinterpret_cast <char *>(&user), sizeof (User));
     }
 }
References User::getNumRecord().
userList()
void DataBase::userList ()
list of the current usersd
Definition at line 136 of file DataBase.cpp.
{
     int posicion = 1;
     for (User u : vectorUser) {
         cout << "\t" << posicion << " -\t" << u.getUserID() << "\t" << u.getUserNIF() << endl;
         posicion += 1;
     }
 }
validUser()
bool DataBase::validUser (int id, int nif)
Validates the users credentials that are stored in the database.
Returns
true
false
Definition at line 39 of file DataBase.cpp.
{
     /*  For each user in the list the atributes ID and NIF are compared whit
         the ones introducted by the user from the login*/
     for (User u : vectorUser) {
         if (u.getUserID() == id && u.getUserNIF() == nif) {
             // when the correct user is found the loop is over
             valided = true;
             if (u.getUserADMIN() == 1) {
                 isAdmin = true;
             } else {
                 isAdmin = false;
             }
             break;
         } else {
             valided = false;
         }
     }
     return valided;
 }
References valided.
writeUsers()
void DataBase::writeUsers ()
Methot used for write in the file users.dat the users at the end of the program.
Definition at line 111 of file DataBase.cpp.
{
     int numRecord = 1;
     fstream outUsersFile ("./resources/users.dat", ios::out | ios::binary | ios::trunc);
     if (!outUsersFile) { // file couldn't be opened
         cerr << "File could not be opened" << endl;
         exit (1);
     }
     for (User u : vectorUser) {
         User user(u.getUserNIF(), u.getUserID(), u.getUserADMIN());
         user.setNumRecord (numRecord);
         outUsersFile.seekp ((user.getNumRecord() - 1 ) *
         sizeof (User));
         outUsersFile.write (reinterpret_cast <const char *> (&user),
         sizeof (User));
         numRecord++;
     }
 }
References User::getNumRecord(), and User::setNumRecord().
Member Data Documentation
actualID
int DataBase::actualID
User that is used to login.
Definition at line 89 of file DataBase.h.
admin
int DataBase::admin
Definition at line 82 of file DataBase.h.
isAdmin
bool DataBase::isAdmin
Definition at line 83 of file DataBase.h.
nuevoID
int DataBase::nuevoID
Definition at line 80 of file DataBase.h.
nuevoNIF
int DataBase::nuevoNIF
Definition at line 81 of file DataBase.h.
valided
bool DataBase::valided
bool to return the
Definition at line 64 of file DataBase.h.
vectorUser
std::set<User> DataBase::vectorUser private
Users storage.
Definition at line 96 of file DataBase.h.
The documentation for this class was generated from the following files:
include/DataBase.h
src/DataBase.cpp